//created on: Nov 30, 2016
package drools

//list any import classes here.

import ftn.uns.ac.rs.tim6.model.*;
import ftn.uns.ac.rs.tim6.dto.*;

//declare any global variables here

rule "osiguranje cena"
dialect "mvel"


    when
    	$insurance : InsurancePriceDto( premiumPrice == 0 )
		
    then
    
  		$insurance.setPremiumPrice( 100 );
  		
  		for(RiskSubcategory risk : $insurance.risks){
  		
  			$insurance.setPremiumPrice($insurance.premiumPrice + risk.coefficient * $insurance.premiumPrice / 100);
  			$insurance.setDiscountPrice($insurance.premiumPrice * 0.1);
  			$insurance.setTaxPrice($insurance.premiumPrice * 0.2);
  			$insurance.setTotalPrice($insurance.premiumPrice - $insurance.discountPrice + $insurance.taxPrice);
  			
  		}
  		System.out.println("premiun: " + $insurance.premiumPrice);
  		System.out.println("popust: " + $insurance.discountPrice);
  		System.out.println("taksa: " + $insurance.taxPrice);
  		System.out.println("ukupno: " + $insurance.totalPrice);
  		  		
end