//created on: Nov 30, 2016
package drools

//list any import classes here.

import ftn.uns.ac.rs.tim6.model.*;
import ftn.uns.ac.rs.tim6.dto.*;

//declare any global variables here

rule "osiguranje cena"
dialect "mvel"


    when
    	$insurance : InsurancePriceDto( premiumPrice == 0 )
		
    then
    
  		$insurance.setPremiumPrice( 100 );
  		
  		for(PricelistItem item : $insurance.items){
  		
  			$insurance.setPremiumPrice($insurance.premiumPrice + item.coefficient * $insurance.premiumPrice / 100);
  			$insurance.setDiscountPrice($insurance.premiumPrice * 0.1);
  			$insurance.setTaxPrice($insurance.premiumPrice * 0.2);
  			$insurance.setTotalPrice($insurance.premiumPrice - $insurance.discountPrice + $insurance.taxPrice);
  			
  		}
  		$insurance.setPremiumPrice(Math.round($insurance.premiumPrice * 100) / 100);
  		$insurance.setDiscountPrice(Math.round($insurance.discountPrice * 100) / 100);
  		$insurance.setTaxPrice(Math.round($insurance.taxPrice * 100) / 100);
  		$insurance.setTotalPrice(Math.round($insurance.totalPrice * 100) / 100);
  		
  		System.out.println("U DROOLS-u");
  		System.out.println("premiun: " + $insurance.premiumPrice);
  		System.out.println("popust: " + $insurance.discountPrice);
  		System.out.println("taksa: " + $insurance.taxPrice);
  		System.out.println("ukupno: " + $insurance.totalPrice);
  		System.out.println("");
  		  		
end